name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Build the Docker image
      run: docker build . --file Dockerfile --tag odai/cordova:latest
    - 
      name: Push the Docker image
      run: docker push odai/cordova
    
